// Generated by Claude Sonnet 4.6
import { pinyin } from 'pinyin-pro'

export function addRubyAnnotations(html: string): string {
  if (typeof window === 'undefined') return html

  const parser = new DOMParser()
  const doc = parser.parseFromString(`<body>${html}</body>`, 'text/html')

  const walker = doc.createTreeWalker(doc.body, NodeFilter.SHOW_TEXT)
  const textNodes: Text[] = []
  let node: Node | null
  while ((node = walker.nextNode())) {
    textNodes.push(node as Text)
  }

  for (const textNode of textNodes) {
    const text = textNode.textContent ?? ''
    if (!text) continue

    const chars = [...text]
    const pinyinArr = pinyin(text, { toneType: 'symbol', type: 'array', traditional: true })

    // Skip nodes that have no CJK characters to annotate
    if (!pinyinArr.some((py, i) => py !== chars[i])) continue

    const fragment = doc.createDocumentFragment()
    chars.forEach((char, i) => {
      const py = pinyinArr[i]
      if (py && py !== char) {
        const ruby = doc.createElement('ruby')
        ruby.appendChild(doc.createTextNode(char))
        const rt = doc.createElement('rt')
        rt.textContent = py
        ruby.appendChild(rt)
        fragment.appendChild(ruby)
      } else {
        fragment.appendChild(doc.createTextNode(char))
      }
    })

    textNode.parentNode?.replaceChild(fragment, textNode)
  }

  return doc.body.innerHTML
}
